<?php

/** * Completely Remove jQuery From WordPress */
function removeJQuery() {
  if (!is_admin()) {
      wp_deregister_script('jquery');
      wp_register_script('jquery', false);
  }
}
add_action('init', 'removeJQuery');

/** * Enable custom logo from admin */
add_theme_support( 'custom-logo');

/** * Enable post thumbnails for post and pages */
add_theme_support( 'post-thumbnails', array( 'post', 'page' ) );

/** * Add before the close body tag the bundle script generated by the others with gulp */
add_action( 'wp_enqueue_scripts', 'registerBundleJS' );
function registerBundleJS() {
  wp_enqueue_script(
    'bundleJS', // name your script so that you can attach other scripts and de-register, etc.
    get_template_directory_uri() . '/bundle.js', NULL, NULL, true
  );
}

/** * Enable Header Menu */
add_action( 'init', 'addHeaderMenu' );
function addHeaderMenu() {
  register_nav_menu('header__menu',__( 'Header Menu' ));
}
 
?>